### ISSUE TITLE
[BUG] script "velcat.sh" não consegue salvar os pares t e v nmo de forma correta

### ISSUE THREAD

**Issue by sanmurilo** [Dirack/proSU#6]
Bug report

O script "velcat.sh" não consegue salvar os pares t e v nmo de forma correta

O script deveria formatar a tabela igual a imagem abaixo.
[velan_velcat.zip](https://github.com/Dirack/proSU/files/4384222/velan_velcat.zip)

![Screenshot from 2020-03-25 20-17-28](https://user-images.githubusercontent.com/23323271/77594976-b2338900-6ed6-11ea-84e0-a29031df742a.png)
![Screenshot from 2020-03-25 20-25-26](https://user-images.githubusercontent.com/23323271/77595007-c7a8b300-6ed6-11ea-9f69-0b874f0926c7.png)

**Comment by Dirack** [comment]
@sanmurilo, quando fizer um bug report pode aproveitar para descrever bem o bug no texto do arquivo Markdown, e não precisa apagar os títulos das seções do template, aqui tem um exemplo na [issue#40](https://github.com/Dirack/Shellinclude/issues/40). 

As seções que descrevem "Como reproduzir o bug" e o "comportamento esperado" são importantes.
