### ISSUE TITLE
[BUG] Análise de velocidade iterativa (iva.scr) 

### ISSUE THREAD

**Issue by sanmurilo** [Dirack/proSU#8]
:bug:  Bug report
o código iva.scr executa com mensagens de erro **(standard_in)** 1: syntax error e algumas vezes não consegue salvar a figura depois da correção NMO **sunmo:** tnmo values must increase monotonically 
**Descreva o bug**
Assim que executo o codigo exibe na tela o erro **(standard_in)** 1: syntax error e algumas vezes não é possível salvar a figura do cdp após a correção NMO (esse bug é provavelmente dá prória função sunmo)  https://github.com/JohnWStockwellJr/SeisUnix/issues/37

**Como reproduzir o bug**

Passos para reproduzir o bug:
1. Vá para '...'
2. Clickar em '....'
3. Scroll down para '....'
4. Veja o erro

**Comportamento esperado**

Uma descrição clara e concisa do que você espera que aconteça.

**Screenshots**
![Screenshot from 2020-03-29 11-44-36](https://user-images.githubusercontent.com/23323271/77853350-219cc780-71ba-11ea-8cd4-a85746bbb698.png)
![Screenshot from 2020-03-29 11-46-18](https://user-images.githubusercontent.com/23323271/77853356-29f50280-71ba-11ea-955d-5059a1258b35.png)

**Desktop (Complete a descrição a seguir):**

 - SO: [e.g. iOS]
 - Versão [e.g. 22]

**Adicione contexto**

Adicione mais informação relevante sobre o problema e o contexto.

**Comment by sanmurilo** [comment]
[iva.zip](https://github.com/Dirack/proSU/files/4399174/iva.zip)

**Comment by sanmurilo** [comment]
https://drive.google.com/open?id=1eKyOUNPK8bpdGPIogbQu1TawIuO0jPWJ

**Comment by Dirack** [comment]
@sanmurilo, corrigi a alimentação dos dados na calculadora bc tente com a seguinte versão e veja se o aviso standard_in sumiu:


[iva.scr.zip](https://github.com/Dirack/proSU/files/4399300/iva.scr.zip)

**Comment by Dirack** [comment]
@sanmurilo, tente utilizar o script iva.sh com a variável $PWD da seguinte forma:

```sh
#!/bin/bash
xterm -geom 122x15+10+640 -e $PWD/iva.scr
```

O xterm utiliza o caminho completo para o script, a variável de ambiente PWD armazena o
caminho absoluto do diretório atual

**Comment by sanmurilo** [comment]
Blz vou testar amanhã de manhã :)

Em dom, 29 de mar de 2020 15:29, Rodolfo Dirack <notifications@github.com>
escreveu:
